name: CI - Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo, pdo_mysql, intl
          coverage: none

      - name: Copy .env and generate key
        run: |
          cp .env.example .env
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Wait for MySQL
        run: sleep 15

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
